### ISSUE TITLE
Render recipes Details component

### ISSUE THREAD

**Issue by moncapitaine** [moncapitaine/cooking-quiz#2]

**Comment by moncapitaine** [comment]
Render a single, hard coded recipe for

Dal 

1. Bereich: Liste der Zuatetn
2. Bereich: Beschreibung der Zubereitung

[Texte z.B. aus </div>](https://www.chefkoch.de/rezepte/2813211433323231/Dal-indisches-Linsengericht.html)

**Comment by Bhoft** [comment]
closed by #7
